# Config file for this raylib testing
# -- WINDOW INFO --
base_width  = 1280
base_height = 720
screen_mode = 0  # 0 for WINDOWED, 1 for EXCLUSIVE FULLSCREEN, 2 for BORDERLESS WINDOWED

# -- FRAMERATE CONFIG --
show_fps_counter = true
lock_framerate   = true  # Locks the framerate to the value of 'target_framerate'
target_framerate = 60    # In Frames Per Second (FPS)
sync_framerate_to_monitor_refresh_rate = true  # Takes precedence over the 'lock_framerate'